#! /usr/bin/env bash
# Makes the man pages for this project more intuitive than those generated by Doxygen
# Uses 'cp' because 'man' doesn't support symlinks
# ...Also pretty much useless, since we already have beautifully generated HTML and LaTeX
# DOESN'T QUITE WORK YET...

if [ "$#" = "0" ]; then
    echo "Please supply a year for which to simplify man pages.";
    exit;
else
    PREFIX_1="./docs$1/man/man7/RJFRC20$1"
    PREFIX_2="./docs$1/man/man7"
fi

for FILE in $PREFIX_1*; do cp $FILE $PREFIX_2/$FILE; done;
