.TH "Autonomous.h" 7 "Thu Jun 23 2011" "Version 2011" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Autonomous.h \- 
.PP
File containing definition of \fIAutonomous\fP class, which is used within the \fIAutomonousPeriodic\fP function in the main program to simplify things.  

.SH SYNOPSIS
.br
.PP
\fC#include 'macros.h'\fP
.br
\fC#include 'Drive.h'\fP
.br
\fC#include 'Manipulator.h'\fP
.br
\fC#include 'Controller.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRJFRC2011::Autonomous\fP"
.br
.RI "\fIClass managing the \fBAutonomous\fP period of the competition. \fP"
.in -1c
.SH "Detailed Description"
.PP 
File containing definition of \fIAutonomous\fP class, which is used within the \fIAutomonousPeriodic\fP function in the main program to simplify things. 

\fBAuthors:\fP
.RS 4
Matthew Haney, Drew Lazzeri 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
