.TH "AxisCameraParams.cpp" 7 "Mon Sep 26 2011" "Version 2011" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AxisCameraParams.cpp \- 
.PP
File patching buggy code for the AxisCameraParams class that causes the robot to freeze. All documentation included was provided by Hurler and/or FIRST, though it was reformatted to be compatible with Doxygen.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Vision/AxisCameraParams.h'\fP
.br
\fC#include 'Vision/AxisCamera.h'\fP
.br
\fC#include <inetLib.h>\fP
.br
\fC#include 'pcre.h'\fP
.br
\fC#include <sockLib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Synchronized.h'\fP
.br
\fC#include 'Timer.h'\fP
.br

.SH "Detailed Description"
.PP 
File patching buggy code for the AxisCameraParams class that causes the robot to freeze. All documentation included was provided by Hurler and/or FIRST, though it was reformatted to be compatible with Doxygen. 

\fBAuthors:\fP
.RS 4
FIRST people, Joe Hurler 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
