.TH "Controller.cpp" 7 "Mon Sep 26 2011" "Version 2011" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller.cpp \- 
.PP
File containing implementations of functions found in the \fIController\fP class (found in \fBController.h\fP)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Controller.h'\fP
.br
\fC#include 'WPILib.h'\fP
.br
\fC#include 'macros.h'\fP
.br

.SH "Detailed Description"
.PP 
File containing implementations of functions found in the \fIController\fP class (found in \fBController.h\fP) 

\fBAuthors:\fP
.RS 4
Matthew Haney, Drew Lazzeri 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
