.TH "Drive.h" 7 "Sun Jul 17 2011" "Version 2011" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drive.h \- 
.PP
File containing definition of \fIDrive\fP class, which is used in the main program to drive the robot in both Autonomous and Teleoperated modes with no waste of memory.  

.SH SYNOPSIS
.br
.PP
\fC#include 'WPILib.h'\fP
.br
\fC#include 'macros.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRJFRC2011::Drive\fP"
.br
.RI "\fIClass abstracting the drive system. \fP"
.in -1c
.SH "Detailed Description"
.PP 
File containing definition of \fIDrive\fP class, which is used in the main program to drive the robot in both Autonomous and Teleoperated modes with no waste of memory. 

\fBAuthors:\fP
.RS 4
Matthew Haney, Drew Lazzeri 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
