.TH "Teleoperated.h" 7 "Thu Jun 23 2011" "Version 2011" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Teleoperated.h \- 
.PP
File containing definition of \fITeleoperated\fP class, which is used in the main program during Teleoperated mode to simplify things.  

.SH SYNOPSIS
.br
.PP
\fC#include 'macros.h'\fP
.br
\fC#include 'WPILib.h'\fP
.br
\fC#include 'Drive.h'\fP
.br
\fC#include 'Manipulator.h'\fP
.br
\fC#include 'Controller.h'\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRJFRC2011::Teleoperated\fP"
.br
.RI "\fIClass managing robot performance in \fBTeleoperated\fP mode. \fP"
.in -1c
.SH "Detailed Description"
.PP 
File containing definition of \fITeleoperated\fP class, which is used in the main program during Teleoperated mode to simplify things. 

\fBAuthors:\fP
.RS 4
Matthew Haney, Drew Lazzeri 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
