.TH "Teleoperated.cpp" 7 "Thu Jun 23 2011" "Version 2011" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Teleoperated.cpp \- 
.PP
File containing definitions of functions declared in class \fITeleoperated\fP (declared in \fBTeleoperated.h\fP).  

.SH SYNOPSIS
.br
.PP
\fC#include 'Teleoperated.h'\fP
.br

.SH "Detailed Description"
.PP 
File containing definitions of functions declared in class \fITeleoperated\fP (declared in \fBTeleoperated.h\fP). 

\fBAuthors:\fP
.RS 4
Matthew Haney, Drew Lazzeri 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
