.TH "MainRobotClass.java" 7 "Sun Oct 16 2011" "Version 2012" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainRobotClass.java \- 
.PP
The main class from which execution starts, as mandated by WPILib.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainRobotClass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main class from which execution starts, as mandated by WPILib. 


.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
