.TH "org::usfirst::frc3729::MainRobotClass" 7 "Sat Dec 3 2011" "Version 2012" "RJHS FRC Software Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::usfirst::frc3729::MainRobotClass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits edu::wpi::first::wpilibj::IterativeRobot.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrobotInit\fP ()"
.br
.ti -1c
.RI "void \fBautonomousPeriodic\fP ()"
.br
.ti -1c
.RI "void \fBteleopPeriodic\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The VM is configured to automatically run this class, and to call the functions corresponding to each mode, as described in the IterativeRobot documentation. If you change the name of this class or the package after creating this project, you must also update the manifest file in the resource directory. 
.SH "Member Function Documentation"
.PP 
.SS "void autonomousPeriodic ()\fC [inline]\fP"This function is called periodically during autonomous 
.SS "void robotInit ()\fC [inline]\fP"This function is run when the robot is first started up and should be used for any initialization code. 
.SS "void teleopPeriodic ()\fC [inline]\fP"This function is called periodically during operator control 

.SH "Author"
.PP 
Generated automatically by Doxygen for RJHS FRC Software Documentation from the source code.
